custom:
  configs:
    aa: dsadsad
    bb: dsadsad
    cc: 111

webSite:
  routes:
    test1:
      template: "/test/test1"
      service: "test/test1"
      parameters:
        curPage: "1"
        pageSize: "100"
    test2:
      template: "/test/test2"
      service: "test/test2"
      parameters:
        curPage: "1"
        pageSize: "100"
swaggerConfig:
  host: localhost:8080

server:
  port: 8080
  session:
    timeout: 10


spring:
  freemarker:
    cache: false
    templateLoaderPath:
      - "classpath:/templates/"
      - "file:templates/"
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**,templates/**

camel:
  springboot:
    name: "test"


logging:
#   config: file:config/logback.xml
    config: classpath:logback.xml